# Generated by Django 5.0.4 on 2024-04-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.TextField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
