# Generated by Django 5.0.4 on 2024-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
